title: Startup Weekend Washington DC Region
description: > # this means to ignore newlines until "baseurl:"
  In just 54 hours, you will experience the highs, lows, fun, and pressure that make up life at a startup. As you learn how to create a real company, you'll meet the very best mentors, investors, cofounders, and sponsors who are ready to help you get started.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.goswdc.co" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'config.rb', 'sass']

enforce_ssl: goswdc.co

facebook:
  app_id: 

logo: "../css/1703_style/img/icon-large.png"

social: 
  name: Your Facebook Page
  link: "https://www.facebook.com/StartupWeekendDC"

include: ['_1703_pages']

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/StartupWeekendDC
  - title: twitter
    url: https://www.twitter.com/sw_dc

# Build settings
markdown: kramdown
permalink: pretty